import PDFDocument from 'pdfkit';

export const generateChallanPDF = (challan: any): Promise<Buffer> => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', (err) => reject(err));

      // Header Banner
      doc
        .fillColor('#1E293B')
        .rect(0, 0, doc.page.width, 90)
        .fill();

      doc
        .fillColor('#FFFFFF')
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('MINI ERP + CRM OPERATIONS PORTAL', 40, 25);

      doc
        .fontSize(12)
        .font('Helvetica')
        .text('Official Sales Challan / Invoice Document', 40, 55);

      // Document Title & Metadata
      doc.fillColor('#0F172A').fontSize(16).font('Helvetica-Bold').text(`SALES CHALLAN: ${challan.challanNumber}`, 40, 110);

      doc.fontSize(10).font('Helvetica').fillColor('#475569');
      doc.text(`Status: ${challan.status}`, 40, 132);
      doc.text(`Date Created: ${new Date(challan.createdAt).toLocaleDateString('en-US', { dateStyle: 'long' })}`, 40, 146);
      doc.text(`Generated By: ${challan.createdBy}`, 40, 160);

      // Customer Details Box
      doc
        .roundedRect(40, 185, doc.page.width - 80, 85, 6)
        .lineWidth(1)
        .strokeColor('#CBD5E1')
        .fillAndStroke('#F8FAFC', '#CBD5E1');

      doc.fillColor('#0F172A').fontSize(11).font('Helvetica-Bold').text('CUSTOMER INFORMATION', 55, 195);
      doc.fontSize(10).font('Helvetica').fillColor('#334155');
      doc.text(`Name: ${challan.customer.name} (${challan.customer.businessName})`, 55, 212);
      doc.text(`Email: ${challan.customer.email} | Mobile: ${challan.customer.mobile}`, 55, 226);
      doc.text(`Type: ${challan.customer.customerType} | GSTIN: ${challan.customer.gstNumber || 'N/A'}`, 55, 240);
      doc.text(`Address: ${challan.customer.address}`, 55, 254);

      // Products Table Header
      let y = 290;
      doc
        .fillColor('#334155')
        .rect(40, y, doc.page.width - 80, 25)
        .fill();

      doc.fillColor('#FFFFFF').fontSize(10).font('Helvetica-Bold');
      doc.text('#', 50, y + 7, { width: 30 });
      doc.text('Product Name / SKU', 80, y + 7, { width: 220 });
      doc.text('Unit Price', 300, y + 7, { width: 80, align: 'right' });
      doc.text('Qty', 390, y + 7, { width: 50, align: 'right' });
      doc.text('Subtotal', 450, y + 7, { width: 95, align: 'right' });

      y += 25;

      // Table Items
      doc.font('Helvetica').fontSize(9).fillColor('#1E293B');

      challan.items.forEach((item: any, index: number) => {
        // Alternate row colors
        if (index % 2 === 0) {
          doc
            .fillColor('#F1F5F9')
            .rect(40, y, doc.page.width - 80, 24)
            .fill();
        }

        doc.fillColor('#1E293B');
        doc.text((index + 1).toString(), 50, y + 6, { width: 30 });
        doc.text(`${item.productName} (${item.productSku})`, 80, y + 6, { width: 220 });
        doc.text(`₹${item.unitPrice.toLocaleString('en-IN')}`, 300, y + 6, { width: 80, align: 'right' });
        doc.text(item.quantity.toString(), 390, y + 6, { width: 50, align: 'right' });
        doc.text(`₹${item.subtotal.toLocaleString('en-IN')}`, 450, y + 6, { width: 95, align: 'right' });

        y += 24;
      });

      // Total summary
      doc.moveTo(40, y + 10).lineTo(doc.page.width - 40, y + 10).strokeColor('#94A3B8').stroke();

      y += 20;

      doc.fontSize(11).font('Helvetica-Bold').fillColor('#0F172A');
      doc.text(`Total Quantity: ${challan.totalQuantity}`, 300, y, { width: 140, align: 'right' });
      doc.text(`Grand Total: ₹${challan.totalAmount.toLocaleString('en-IN')}`, 440, y, { width: 105, align: 'right' });

      // Footer Signatures
      y += 80;
      doc.fontSize(9).font('Helvetica').fillColor('#64748B');
      doc.text('Authorized Signatory', 60, y);
      doc.text('Receiver / Customer Signature', 380, y);
      doc.moveTo(50, y - 5).lineTo(180, y - 5).strokeColor('#CBD5E1').stroke();
      doc.moveTo(370, y - 5).lineTo(500, y - 5).strokeColor('#CBD5E1').stroke();

      doc.text('Thank you for doing business with us! This is a system-generated sales challan.', 40, doc.page.height - 35, {
        align: 'center',
        width: doc.page.width - 80,
      });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
};
