import React, { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { challanAPI } from '../services/api';
import { Challan } from '../types';
import { Badge } from '../components/Badge';
import { ArrowLeft, Download, CheckCircle, XCircle, Building, User, FileText, Calendar, AlertTriangle } from 'lucide-react';

export const ChallanDetailPage: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const [challan, setChallan] = useState<Challan | null>(null);
  const [loading, setLoading] = useState(true);
  const [updatingStatus, setUpdatingStatus] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');

  const fetchChallanDetail = async () => {
    if (!id) return;
    setLoading(true);
    try {
      const res = await challanAPI.getChallanById(id);
      setChallan(res.data);
    } catch (err) {
      console.error('Failed to load challan detail', err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchChallanDetail();
  }, [id]);

  const handleUpdateStatus = async (newStatus: 'CONFIRMED' | 'CANCELLED') => {
    if (!id) return;
    setErrorMsg('');
    setUpdatingStatus(true);

    try {
      await challanAPI.updateChallanStatus(id, newStatus);
      fetchChallanDetail();
    } catch (err: any) {
      const msg = err.response?.data?.message || 'Failed to update challan status';
      const errors = err.response?.data?.errors;
      if (Array.isArray(errors)) {
        setErrorMsg(`${msg}: ${errors.join('; ')}`);
      } else {
        setErrorMsg(msg);
      }
    } finally {
      setUpdatingStatus(false);
    }
  };

  if (loading) {
    return <div style={{ padding: '2rem', textAlign: 'center', color: 'var(--text-muted)' }}>Loading challan document...</div>;
  }

  if (!challan) {
    return (
      <div style={{ padding: '2rem', textAlign: 'center' }}>
        <h2>Challan Not Found</h2>
        <Link to="/challans" className="btn btn-secondary" style={{ marginTop: '1rem' }}>
          Back to Sales Challans
        </Link>
      </div>
    );
  }

  return (
    <div>
      <div style={{ marginBottom: '1.25rem' }}>
        <Link to="/challans" className="btn btn-secondary btn-sm" style={{ gap: '0.35rem' }}>
          <ArrowLeft size={14} />
          <span>Back to Sales Challans</span>
        </Link>
      </div>

      {errorMsg && (
        <div className="alert-banner alert-banner-danger" style={{ marginBottom: '1.25rem' }}>
          <AlertTriangle size={18} />
          <span>{errorMsg}</span>
        </div>
      )}

      <div className="page-header">
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem' }}>
            <h1>{challan.challanNumber}</h1>
            <Badge type={challan.status} />
          </div>
          <p className="page-subtitle" style={{ display: 'flex', alignItems: 'center', gap: '0.5rem', marginTop: '0.35rem' }}>
            <Calendar size={15} />
            <span>Created on {new Date(challan.createdAt).toLocaleString('en-US', { dateStyle: 'long', timeStyle: 'short' })}</span>
            <span>• Generated by {challan.createdBy}</span>
          </p>
        </div>

        <div style={{ display: 'flex', gap: '0.75rem' }}>
          <a
            href={challanAPI.getPDFUrl(challan.id)}
            target="_blank"
            rel="noreferrer"
            className="btn btn-primary"
          >
            <Download size={16} />
            <span>Export Official PDF</span>
          </a>

          {challan.status === 'DRAFT' && (
            <>
              <button
                className="btn btn-success"
                onClick={() => handleUpdateStatus('CONFIRMED')}
                disabled={updatingStatus}
              >
                <CheckCircle size={16} />
                <span>Confirm & Deduct Stock</span>
              </button>

              <button
                className="btn btn-danger"
                onClick={() => handleUpdateStatus('CANCELLED')}
                disabled={updatingStatus}
              >
                <XCircle size={16} />
                <span>Cancel Challan</span>
              </button>
            </>
          )}

          {challan.status === 'CONFIRMED' && (
            <button
              className="btn btn-danger"
              onClick={() => handleUpdateStatus('CANCELLED')}
              disabled={updatingStatus}
            >
              <XCircle size={16} />
              <span>Cancel & Restore Stock</span>
            </button>
          )}
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: '1fr 2fr', gap: '1.5rem' }}>
        {/* Customer Information Card */}
        <div className="card" style={{ height: 'fit-content' }}>
          <h3 style={{ marginBottom: '1rem', borderBottom: '1px solid var(--border-color)', paddingBottom: '0.5rem' }}>
            Customer Information
          </h3>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem', fontSize: '0.875rem' }}>
            <div>
              <span className="form-label">Customer Name</span>
              <div style={{ fontWeight: 700, fontSize: '1rem', display: 'flex', alignItems: 'center', gap: '0.4rem' }}>
                <User size={16} style={{ color: 'var(--accent-primary)' }} />
                <span>{challan.customer.name}</span>
              </div>
            </div>

            <div>
              <span className="form-label">Business Name</span>
              <div style={{ display: 'flex', alignItems: 'center', gap: '0.4rem', color: 'var(--text-muted)' }}>
                <Building size={16} />
                <span>{challan.customer.businessName}</span>
              </div>
            </div>

            <div>
              <span className="form-label">Contact Details</span>
              <div style={{ color: 'var(--text-muted)' }}>Mobile: {challan.customer.mobile}</div>
              <div style={{ color: 'var(--text-muted)' }}>Email: {challan.customer.email}</div>
            </div>

            <div>
              <span className="form-label">GSTIN / Type</span>
              <div style={{ color: 'var(--text-muted)' }}>
                {challan.customer.gstNumber || 'N/A'} ({challan.customer.customerType})
              </div>
            </div>

            <div>
              <span className="form-label">Shipping Address</span>
              <div style={{ color: 'var(--text-muted)', lineHeight: '1.5' }}>{challan.customer.address}</div>
            </div>
          </div>
        </div>

        {/* Itemized Snapshot Table */}
        <div className="card">
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '1rem' }}>
            <h3>Itemized Snapshot Products</h3>
            <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>
              Note: Retains original pricing at creation time.
            </span>
          </div>

          <div className="table-responsive">
            <table className="table">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Product Name</th>
                  <th>SKU</th>
                  <th>Unit Price</th>
                  <th>Quantity</th>
                  <th style={{ textAlign: 'right' }}>Subtotal</th>
                </tr>
              </thead>
              <tbody>
                {challan.items.map((item, index) => (
                  <tr key={item.id}>
                    <td style={{ color: 'var(--text-dim)' }}>{index + 1}</td>
                    <td style={{ fontWeight: 700 }}>{item.productName}</td>
                    <td style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>{item.productSku}</td>
                    <td>₹{item.unitPrice.toLocaleString('en-IN')}</td>
                    <td style={{ fontWeight: 700 }}>{item.quantity} pcs</td>
                    <td style={{ textAlign: 'right', fontWeight: 800 }}>₹{item.subtotal.toLocaleString('en-IN')}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div
            style={{
              marginTop: '1.5rem',
              padding: '1.25rem',
              backgroundColor: 'var(--bg-input)',
              borderRadius: 'var(--radius-md)',
              border: '1px solid var(--border-color)',
              display: 'flex',
              justifyContent: 'space-between',
              alignItems: 'center',
            }}
          >
            <div>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Total Items Count</div>
              <div style={{ fontSize: '1.1rem', fontWeight: 800 }}>{challan.totalQuantity} pcs</div>
            </div>

            <div style={{ textAlign: 'right' }}>
              <div style={{ fontSize: '0.85rem', color: 'var(--text-muted)' }}>Grand Total Amount</div>
              <div style={{ fontSize: '1.6rem', fontWeight: 800, color: 'var(--accent-primary)' }}>
                ₹{challan.totalAmount.toLocaleString('en-IN')}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
